#version 460

#extension GL_ARB_bindless_texture : require

#define M_PI 3.14159265358979323846
#define MAX_LIGHTS_PER_TILE 1024
#define TILE_SIZE 16

uniform layout(binding = 0) writeonly image2D transmitanceTexture;
uniform layout(binding = 1) sampler2D depthTexture;
uniform layout(binding = 2) sampler2D directionalLightShadowTexture;
uniform layout(binding = 3) sampler2D sceneTexture;

uniform layout(location = 0) mat4 projection;
uniform layout(location = 1) mat4 inverseViewMatrix;
uniform layout(location = 2) vec3 cameraPosition;

uniform layout(location = 3) int NUM_STEPS;
uniform layout(location = 4) float fogIntensity;
uniform layout(location = 5) float extinctionCoefficient;
uniform layout(location = 6) float frameTime;
uniform layout(location = 7) float noiseAmmount;
uniform layout(location = 8) float anisotropy;

// TESTING LAYOUTS -> LATER SHOULD BE INCLUDED IN A BUFFER / UNIFORM


// ONLY ONE SPOT, JUST FOR TESTING -> MOVE TO SPOT LIGHTS BUFFER AND MAKE TEXTURE RESIDENT SO IT CAN BE ACCESED
uniform layout(binding = 9) sampler2D spotTexture;

// DIRECTIONAL LIGHT MATRICES -> MOVE TO UNIFORM OF DIRECTIONAL
uniform layout(location = 10) mat4 directinal_View_Mat;
uniform layout(location = 11) mat4 directinal_Projection_Mat;
uniform layout(location = 12) int numTilesX;

struct PointLight
{
	vec4 position;		// xyz = position & w = range
	vec4 color;			// rgb = color & alpha = intensity 
};

struct SpotLight
{
	vec4 position;		// xyz = position & w = range
	vec4 color;			// rgb = color & alpha = intensity
	vec3 direction;	
	float innerAngle;
	float outerAngle;
	int spotShadowIndex;
};

struct VisibleIndex {
	int index;
};

struct SpotShadow {
	mat4 shadowViewProj;
    sampler2D spotShadowMap;
};

layout(std140, binding = 3) uniform Directional
{
    vec4 directional_dir;
    vec4 directional_color;
};

readonly layout(std430, binding = 4) buffer PointLights
{
	int pointLightsCount;
	PointLight pointLights[];
};

readonly layout(std430, binding = 5) buffer SpotLights
{
	int spotLightsCount;
	SpotLight spotLights[];
};

layout(std430, binding = 6) readonly buffer VisibleLightIndicesBuffer {
    int visibleIndices[];
};

layout(std430, binding = 7) readonly buffer SpotLightShadowBuffer {
    SpotShadow spotShadows[];
};


layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

float rand(vec2 co){return fract(sin(dot(co.xy ,vec2(12.9898,78.233))) * 43758.5453);}
float rand (vec2 co, float l) {return rand(vec2(rand(co), l));}
float rand (vec2 co, float l, float t) {return rand(vec2(rand(co, l), t));}

vec3 GetWorldPosition(float depth, vec2 uv)
{
    float a = projection[3][2];
    float b = projection[2][2];

    float zView = - a / ((depth * 2.0 - 1.0) + b);
    
    a = projection[0][0];
    b = projection[1][1];

    float xView = (-zView / a) * (uv.x * 2.0 - 1.0);
    float yView = (-zView / b) * (uv.y * 2.0 - 1.0);

    vec4 worldPosition = inverseViewMatrix *  vec4(xView,yView,zView, 1.0);

    return worldPosition.xyz;
}

// THIS IS TEMPORAL, LATER USE A TEXTURE, SHOULD IMPROVE PERFORMANCE
float noise(vec3 currentPosition, float time)
{
    vec2 pos = floor(currentPosition.xy * currentPosition.z);
	vec2 posx = pos + vec2(1.0, 0.0);
	vec2 posy = pos + vec2(0.0, 1.0);
	vec2 posxy = pos + vec2(1.0);
	
	float c = rand(pos, currentPosition.z, time);
	float cx = rand(posx, currentPosition.z, time);
	float cy = rand(posy, currentPosition.z, time);
	float cxy = rand(posxy, currentPosition.z, time);
	
	vec2 d = fract(currentPosition.xy * currentPosition.z);
	d = -0.5 * cos(d * M_PI) + 0.5;
	
	float ccx = mix(c, cx, d.x);
	float cycxy = mix(cy, cxy, d.x);
	float center = mix(ccx, cycxy, d.y);
	
	return center * 2.0 - 1.0;
}

float SpotLightAttenuation(const int index, vec3 pos)
{
	const vec3 dirLight = normalize(spotLights[index].direction);
	const float dist = dot(pos - spotLights[index].position.xyz, dirLight);
	const float Fatt = pow(max(1 - pow((dist / spotLights[index].position.w), 4.0), 0.0), 2.0) / (pow(dist, 2.0) + 1.0);

	const vec3 D = normalize(pos - spotLights[index].position.xyz);
	const float C = dot(D, dirLight);

	const float cosInner = cos(radians(spotLights[index].innerAngle));
	const float cosOuter = cos(radians(spotLights[index].outerAngle));
	float Catt = 0;
	if (C > cosInner) Catt = 1;
	else if (C < cosInner && C > cosOuter) Catt = (C - cosOuter) / (cosInner - cosOuter);

	return Fatt * Catt;
}

bool ValidProjectionCoordinates(vec3 projCoords)
{
    return projCoords.x >= 0.0 && projCoords.x <= 1.0 && projCoords.y >= 0.0 && projCoords.y <= 1.0 && projCoords.z >= 0.0 && projCoords.z <= 1.0;
}

float CalculateExtinctionCoefficient(vec3 currentPosition)
{
    return extinctionCoefficient * noise(currentPosition, frameTime) * noiseAmmount;
}

float ScatteringPhaseFunction(vec3 viewDirection, vec3 lightDirection)
{
    float k = 1.55 * anisotropy - 0.55 * anisotropy * anisotropy * anisotropy;
    float theta = dot(viewDirection, lightDirection);

    return (1 - k * k) / (4 * M_PI * (1 + k * cos(theta)) * (1 + k * cos(theta)));
}

vec3 CalculateInScattering(vec3 currentPosition, vec3 rayDirection, vec2 uvCoords, int baseOffset)
{
    vec3 light = vec3(0.0);
    rayDirection = normalize(rayDirection);

    vec4 currentPosFromLight;
    vec3 projCoords;

    // DIRECTIONAL LIGHT
    // currentPosFromLight = directinal_Projection_Mat * directinal_View_Mat * vec4(currentPosition, 1.0);
    // projCoords = currentPosFromLight.xyz / currentPosFromLight.w;
    // projCoords = projCoords * 0.5 + 0.5;

    // if(ValidProjectionCoordinates(projCoords))
    // {
    //     float dLightVisibility = texture(directionalLightShadowTexture, projCoords.xy).r;
    //     if(projCoords.z > dLightVisibility )
    //         light += ScatteringPhaseFunction(-rayDirection, normalize(directional_dir.xyz)) * directional_color.rgb * directional_color.w;
    // }

    for(int i = 0; i < MAX_LIGHTS_PER_TILE; ++i)
    {
        int lightIndexBuffer = visibleIndices[baseOffset + i];

        if(lightIndexBuffer == -1) break;

        bool isSpot = (lightIndexBuffer & 0x80000000) != 0;
        int realIndex = lightIndexBuffer & 0x7FFFFFFF;
        if(isSpot)
        {
            int shadowIndex = spotLights[realIndex].spotShadowIndex;
            
            if(shadowIndex < 0) continue;

            currentPosFromLight = spotShadows[shadowIndex].shadowViewProj * vec4(currentPosition, 1.0);
            projCoords = currentPosFromLight.xyz / currentPosFromLight.w;
            projCoords = projCoords * 0.5 + 0.5;

            if(ValidProjectionCoordinates(projCoords))
            {
                float lightVisible =  texture(spotShadows[shadowIndex].spotShadowMap, projCoords.xy).r;
                // return spotLights[realIndex].color.rgb * spotLights[realIndex].color.a;

                if(projCoords.z < lightVisible)
                {
                    const float attenuation = SpotLightAttenuation(realIndex, currentPosition);
                    const vec3 spotColor = spotLights[realIndex].color.rgb * spotLights[realIndex].color.a * attenuation;

                    float spotScattering = ScatteringPhaseFunction(-rayDirection, normalize(spotLights[realIndex].direction));

                    light += spotColor * spotScattering;
                }
            }
        }
    }
    
    return light;
}

float sampleIGN(vec2 pixelXY, float time)
{
    pixelXY += (time * 5.588238f );
    return fract(52.9829189f * fract(0.06711056f*float(pixelXY.x) + 0.00583715f*float(pixelXY.y)));
}

// RETURNS NUMBER OF INTERSECTIONS, RESULT SHOULD BE 0, 1 OR 2;
// IF 0 -> DON'T USE T0 OR T1
// IF 1 -> USE T0
// IF 2 -> USE T0 AND T1
int ConeIntersection(in vec3 conePosition, in vec3 coneDirection, in float coneAngle, in float coneLength, in vec3 rayOrigin, in vec3 rayDirection, out float t0, out float t1)
{
    int totalIntersections = 0;

    float dotDV = dot(rayDirection, coneDirection);
    float coneCosine = cos(radians(coneAngle));
    vec3 CO = rayOrigin - conePosition;
    float dotCO_V = dot(CO, coneDirection);

    float a = dotDV * dotDV - coneCosine * coneCosine;
    float b = 2.0 * (dotDV * dotCO_V - dot(rayDirection, CO) * coneCosine * coneCosine);
    float c = dotCO_V * dotCO_V - dot(CO, CO) * coneCosine * coneCosine;

    float determinant = b*b - 4.0 * a * c;

    if(determinant  == 0)
    {
        t0 = -b / (2 * a);

        vec3 point = conePosition + coneDirection * t0;
        float dist = dot(point - conePosition, coneDirection);

        if(dist > 0 && dist < coneLength) ++totalIntersections;
    }
    else if(determinant > 0)
    {
        float determinantSqrt = sqrt(determinant);
        
        //t0 check
        float auxTime = (-b - determinantSqrt) / (2.0 * a);
        vec3 point = conePosition + coneDirection * auxTime;
        float dist = dot(point - conePosition, coneDirection);

        if(dist > 0 && dist < coneLength)
        {
            t0 = auxTime;
            ++totalIntersections;
        }

        //t1 check
        auxTime = (-b + determinantSqrt) / (2.0 * a);
        point = conePosition + coneDirection * auxTime;
        dist = dot(point - conePosition, coneDirection);

        if(dist > 0 && dist < coneLength)
        {
            if(auxTime < t0)
            {
                t1 = t0;
                t0 = auxTime;
            }
            else
            {
                t1 = auxTime;
            }

            ++totalIntersections;
        }
    }

    return totalIntersections;
}

bool SolveQuadratic(in float a, in float b, in float c, out float t0, out float t1)
{
    float discr = b * b - 4 * a * c;

    if (discr < 0) return false;

    else if (discr == 0) t0 = t1 = - 0.5 * b / a;

    else 
    {
        float discrSqrt = sqrt(discr);
        float q;

        if(b > 0)  q = -0.5 * (b + discrSqrt);
        else q = -0.5 * (b - discrSqrt); 
        
        t0 = q / a;
        t1 = c / q;
    }

    if (t0 > t1)
    {
        float tmp = t0;
        t0 = t1;
        t1 = tmp;
    }
    
    return true;
}

bool SpehereIntersection(vec3 center, float radius, vec3 rayOrigin, vec3 rayDirection, out float t0, out float t1)
{
    vec3 L = rayOrigin - center;
    float a = dot(rayDirection, rayDirection); // JUST IN CASE THEY ARE NOT NORMALIZED
    float b = 2.0 * dot(rayDirection, L);
    float c = dot(L, L) - (radius * radius);
    
    if(!SolveQuadratic(a, b, c, t0, t1)) return false;

    if (t0 > t1)
    {
        float tmp = t0;
        t0 = t1;
        t1 = tmp;
    }

    if (t0 < 0) 
    {
        t0 = t1; // If t0 is negative, let's use t1 instead.
        if (t0 < 0) return false; // Both t0 and t1 are negative.
    }

    return true;
}

// bool RayIntersectionPoints(in vec3 rayOrigin, in vec3 rayDirection, out float t0, out float t1)
// {

// }

void main()
{
    const ivec2 textureSize = imageSize(transmitanceTexture);

    if(gl_GlobalInvocationID.x < textureSize.x && gl_GlobalInvocationID.y < textureSize.y)
    {
	    ivec2 tileCoord = ivec2(gl_GlobalInvocationID.xy) / TILE_SIZE;
	    int tileIndex = tileCoord.y * numTilesX + tileCoord.x;
        int baseOffset = tileIndex * MAX_LIGHTS_PER_TILE;

        vec2 uvCoords = vec2(gl_GlobalInvocationID.x / float(textureSize.x), gl_GlobalInvocationID.y / float(textureSize.y));
        float depth = texture(depthTexture, uvCoords).r;
        
        vec3 worldPosition = GetWorldPosition(depth, uvCoords);

        vec3 rayDirection = worldPosition - cameraPosition;

        vec3 marchingStep = rayDirection / float(NUM_STEPS);
        float stepSize = length(marchingStep);

        vec3 currentPosition = cameraPosition + marchingStep * sampleIGN(gl_GlobalInvocationID.xy, frameTime);

        float accExtintionCoeff = 0.0;
        vec3 accInScattering = vec3(0.0);

        for(int i = 0; i < NUM_STEPS; ++i)
        {
            accExtintionCoeff += CalculateExtinctionCoefficient(currentPosition) * stepSize;
            accInScattering += CalculateInScattering(currentPosition, rayDirection, uvCoords, baseOffset) * stepSize * exp(-accExtintionCoeff);

            currentPosition += marchingStep;
        }

        vec3 finalInScattering = accInScattering * fogIntensity;

        vec4 originalColor = texture(sceneTexture, uvCoords);

        if(depth < 1.f)
        {
            imageStore(transmitanceTexture, ivec2(gl_GlobalInvocationID.xy), vec4(originalColor.rgb + finalInScattering, 1.0));
        }
        else
        {
            imageStore(transmitanceTexture, ivec2(gl_GlobalInvocationID.xy), originalColor);
        }

        // imageStore(transmitanceTexture, ivec2(gl_GlobalInvocationID.xy), vec4(vec3(depth), 1.0));
    }
}